BEGIN TRANSACTION;

INSERT INTO propriete_medicinale ( nom_propriete ) VALUES 
( 'Antioxydante' ),
( 'Répulsif puceron' ),
( 'Aide digestion' ),
( 'Anti-inflammatoire' ),
( 'Répulsif pucerons aleurodes' ),
( 'Ornamental' ),
( 'Mellifère' ),
( 'Digestive' ),
( 'Antimicrobienne' ),
( 'Antifongique' ),
( 'Antibactérienne' ),
( 'Stimulante' ),
( 'Richesse oméga-3' ),
( 'Immunité' ),
( 'Tonique' ),
( 'Carminative' ),
( 'Photosensibilisante' ),
( 'Tisane' ),
( 'Ornementale' ),
( 'Antispasmodique' ),
( 'Antivirale' ),
( 'Calmante' ),
( 'Rafraîchissante' ),
( 'Riche vitamines A C K' ),
( 'Minéraux calcium fer magnésium' ),
( 'Riche vitamines minéraux' ),
( 'Diurétique' ),
( 'Riche vitamines A C' ),
( 'Fer' ),
( 'Tonifiante' ),
( 'Aromatique noisette moutarde' ),
( 'Production continue' ),
( 'Sécheresse tolérance' ),
( 'Expectorant' ),
( 'Miel foie' ),
( 'Aromatique fin' ),
( 'Vitamines A C K' ),
( 'Minéraux calcium fer potassium' ),
( 'Répulsif limaces' ),
( 'Saveur oignon doux ail' ),
( 'Compagne carotte' ),
( 'Dépurative' ),
( 'Apéritive' ),
( 'Riche oligo-éléments' ),
( 'Laxatif' ),
( 'Saveur céleri doux' ),
( 'Rustique froid' ),
( 'Attirant pollinisateurs' ),
( 'Saveur wasabi piquante' ),
( 'Riche antioxydants vitamines minéraux' ),
( 'Anti-âge naturel' ),
( 'Huile essentielle' ),
( 'Arôme curry puissant' ),
( 'Antiquité' ),
( 'Relaxante' ),
( 'Anisée fraîche' ),
( 'Détoxifiante' ),
( 'Purifiante' ),
( 'Goût ail subtil ciboulette' ),
( 'Arôme thym unique' ),
( 'Arôme citron frais' ),
( 'Répulsif moustiques' ),
( 'Riche carvacrol thymol' ),
( 'Italienne grecque' ),
( 'Répulsif pucerons fourmis' ),
( 'Adaptogène' ),
( 'Anti-stress' ),
( 'Anti-anxiété' ),
( 'Médecine ayurvédique' ),
( 'Anti-maux tête' ),
( 'Apaisante stress nerveuse' ),
( 'Sommeil' ),
( 'Compresses irritations' ),
( 'Stimulante appétit' ),
( 'Élimination toxines' ),
( 'Apaisante gorge' ),
( 'Médecine ancienne' ),
( 'Riche artémisinine' ),
( 'Antipaludéenne' ),
( 'Médecine asiatique' ),
( 'Antiseptique' );

COMMIT;