export const METIER = {
  LOGIN_INCORRECT: 'LOGIN_INCORRECT',

  DUPLICATE_ESPECE: 'DUPLICATE_ESPECE',
  ESPECE_HAS_VARIETES: 'ESPECE_HAS_VARIETES',

  DUPLICATE_CATEGORY: 'DUPLICATE_CATEGORY',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  SAME_CATEGORY: 'SAME_CATEGORY',
  DESTINATION_CATEGORY_NOT_FOUND: 'DESTINATION_CATEGORY_NOT_FOUND',

  DUPLICATE_VARIETE: 'DUPLICATE_VARIETE',
  VARIETE_HAS_PRODUCTS: 'VARIETE_HAS_PRODUCTS',

  DUPLICATE_PRODUCT: 'DUPLICATE_PRODUCT',

  DUPLICATE_USER_EMAIL: 'DUPLICATE_USER_EMAIL',

  DUPLICATE_LOCALITE: 'DUPLICATE_LOCALITE',
  LOCALITE_HAS_ADRESSES: 'LOCALITE_HAS_ADRESSES',

  DUPLICATE_AVIS: 'DUPLICATE_AVIS',
  AVIS_NOT_FOUND: 'AVIS_NOT_FOUND',
} as const;

export const TECHNIQUES = {

  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',

  ESPECE_CREATE_ERROR: 'ESPECE_CREATE_ERROR',
  ESPECE_UPDATE_ERROR: 'ESPECE_UPDATE_ERROR',
  ESPECE_DELETE_ERROR: 'ESPECE_DELETE_ERROR',

  CATEGORY_CREATE_ERROR: 'CATEGORY_CREATE_ERROR',
  CATEGORY_UPDATE_ERROR: 'CATEGORY_UPDATE_ERROR',
  CATEGORY_DELETE_ERROR: 'CATEGORY_DELETE_ERROR',
  CATEGORY_DELETE_WITH_REAFFECTATION_ERROR: 'CATEGORY_DELETE_WITH_REAFFECTATION_ERROR',

  VARIETE_CREATE_ERROR: 'VARIETE_CREATE_ERROR',
  VARIETE_UPDATE_ERROR: 'VARIETE_UPDATE_ERROR',
  VARIETE_DELETE_ERROR: 'VARIETE_DELETE_ERROR',

  PRODUCT_CREATE_ERROR: 'PRODUCT_CREATE_ERROR',
  PRODUCT_UPDATE_ERROR: 'PRODUCT_UPDATE_ERROR',
  PRODUCT_DELETE_ERROR: 'PRODUCT_DELETE_ERROR',

  USER_CREATE_ERROR: 'USER_CREATE_ERROR',
  USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',
  USER_DELETE_ERROR: 'USER_DELETE_ERROR',

  LOCALITE_CREATE_ERROR: 'LOCALITE_CREATE_ERROR',
  LOCALITE_UPDATE_ERROR: 'LOCALITE_UPDATE_ERROR',
  LOCALITE_DELETE_ERROR: 'LOCALITE_DELETE_ERROR',

  ADRESSE_CREATE_ERROR: 'ADRESSE_CREATE_ERROR',
  ADRESSE_UPDATE_ERROR: 'ADRESSE_UPDATE_ERROR',
  ADRESSE_DELETE_ERROR: 'ADRESSE_DELETE_ERROR',

  AVIS_CREATE_ERROR: 'AVIS_CREATE_ERROR',
  AVIS_UPDATE_ERROR: 'AVIS_UPDATE_ERROR',
  AVIS_DELETE_ERROR: 'AVIS_DELETE_ERROR',
  AVIS_LIKE_ERROR: 'AVIS_LIKE_ERROR',

} as const;

type ErreurMetier = typeof METIER[keyof typeof METIER];
type ErreurTechnique = typeof TECHNIQUES[keyof typeof TECHNIQUES];

export function gererErreurPrisma(
  error: unknown, erreursMetier: ErreurMetier[], erreurTechnique: ErreurTechnique): never {

  if (error instanceof Error && erreursMetier.includes(error.message as ErreurMetier)) {
    throw error;
  }

  throw new Error(erreurTechnique);
}