PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

INSERT INTO espece ( nom_scientifique, nom_commun, type_plante ) VALUES
	 ('Solanum lycopersicum','Tomate','maraîchère'),
	 ('Solanum pimpinellifolium','Tomate Groseille','maraîchère'),
	 ('Solanum melongena','Aubergine','maraîchère'),
	 ('Cyclanthera pedata','Concombrespecee grimpant','maraîchère'),
	 ('Cucumis sativus','Concombre','maraîchère'),
	 ('Melothria scabra','Mélothérie','maraîchère'),
	 ('Cucurbita maxima','Potiron','maraîchère'),
	 ('Cucurbita pepo','Courgette','maraîchère'),
	 ('Cucumis melo','Melon','maraîchère'),
	 ('Citrullus lanatus','Pastèque','maraîchère'),
	 ('Capsicum chinense','Piment','maraîchère'),
	 ('Capsicum annuum','Piment','maraîchère'),
	 ('Vicia faba','Fève','maraîchère'),
	 ('Phaseolus vulgaris','Haricot','maraîchère'),
	 ('Lens culinaris','Lentille','maraîchère'),
	 ('Zea mays','Maïs','maraîchère'),
	 ('Pisum sativum','Pois','maraîchère'),
	 ('Ocimum basilicum','Basilic','maraîchère'),
	 ('Coriandrum sativum','Coriandre','maraîchère'),
	 ('Petroselinum crispum','Persil','maraîchère'),
	 ('Eruca sativa','Roquette','maraîchère'),
	 ('Satureia hortensis','Sarriette','maraîchère'),
	 ('Perilla frutescens var. crispa purpurea','Perilla','maraîchère'),
	 ('Allium tuberosum','Ail chinois','maraîchère'),
	 ('Angelica Archangelica','Angélique','maraîchère'),
	 ('Allium schoeneprasum','Ciboulette','maraîchère'),
	 ('Foeniculum vulgare purpurascens','Fenouil','maraîchère'),
	 ('Melissa officinalis','Mélisse','maraîchère'),
	 ('Mentha spicata','Menthe','maraîchère'),
	 ('Rumex acetosa','Oseille','maraîchère'),
	 ('Diplotaxis tenuifolia','Roquette sauvage','maraîchère'),
	 ('Thymus vulgaris','Thym','maraîchère'),
	 ('Anthriscus cerefolium','Cerfeuil','maraîchère'),
	 ('Allium fistulosum','Ciboule','maraîchère'),
	 ('Trigonella foenum-graecum','Fenugrec','maraîchère'),
	 ('Apium graveolens seclinum','Per-cel','maraîchère'),
	 ('Helichrysum italicum','Plante curry','maraîchère'),
	 ('Verbena officinalis','Verveine','maraîchère'),
	 ('Origanum marjorana','Marjolaine','maraîchère'),
	 ('Anethum graveolens','Aneth','maraîchère'),
	 ('Allium ursinum','Ail des ours','maraîchère'),
	 ('Ocimum americanum','Basilic citron','maraîchère'),
	 ('Origanum vulgare','Origan','maraîchère'),
	 ('Satureia montana','Sarriette des montagnes','maraîchère'),
	 ('Tanacetum parthenium','Grande camomille','maraîchère'),
	 ('Matricaria chamomilla','Camomille matricaire','maraîchère'),
	 ('Levisticum officinale','Livèche','maraîchère'),
	 ('Salvia officinalis','Sauge','maraîchère'),
	 ('Artemisia annua','Armoise','maraîchère'),
	 ('Beta vulgaris','Betterave','maraîchère'),
	 ('Daucus carota','Carotte','maraîchère'),
	 ('Brassica rapa','Navet','maraîchère'),
	 ('Chaerophyllum bulbosum','Cerfeuil tubéreux','maraîchère'),
	 ('Allium cepa','Oignon','maraîchère'),
	 ('Pastinaca sativa','Panais','maraîchère'),
	 ('Raphanus sativus','Radis','maraîchère'),
	 ('Tragopogon porrifolium','Salsifis','maraîchère'),
	 ('Cynara cardunculus','Artichaut','maraîchère'),
	 ('Apium graveolens','Céleri à côtes','maraîchère'),
	 ('Cichorium intybus','Chicorée radicchio','maraîchère'),
	 ('Cichorium endivia','Chicorées frisées et scaroles','maraîchère'),
	 ('Beta vulgaris','Côte de bette','maraîchère'),
	 ('Spinacea oleracea','Épinard','maraîchère'),
	 ('Chenopodium capitatum','Épinard fraise','maraîchère'),
	 ('Rumex patienta','Épinard oseille','maraîchère'),
	 ('Brassica oleracea botrytis cymosa','Chou brocoli','maraîchère'),
	 ('Brassica oleracea botrytis','Chou fleur','maraîchère'),
	 ('Brassica oleracea var. italica','Chou brocoli violet du Cap','maraîchère'),
	 ('Brassica oleracea acephala sabellica','Chou frisé Kale','maraîchère'),
	 ('Brassica oleracea capitata alba','Chou cabu blanc','maraîchère'),
	 ('Brassica oleracea capitata rubra','Chou cabu rouge','maraîchère'),
	 ('Brassica oleracea capitata sabauda','Chou de Milan','maraîchère'),
	 ('Brassica pekinensis','Chou chinois','maraîchère'),
	 ('Brassica rapa rosularis','Pak Choi Taisai','maraîchère'),
	 ('Brassica rapa chinensis','Pak Choï Red Inferno','maraîchère'),
	 ('Brassica oleracea gemmifera','Chou fleur','maraîchère'),
	 ('Brassica campestris','Chou-navet','maraîchère'),
	 ('Brassica oleracea gongylodes','Chou-rave','maraîchère'),
	 ('Lactuca sativa','Laitue','maraîchère'),
	 ('Valerianella locusta','Mâche, valérianelle','maraîchère'),
	 ('Allium porrum','Poireau','maraîchère'),
	 ('Rheum','Rhubarbe','maraîchère'),
	 ('Brassica juncea','Moutarde de Chine','maraîchère'),
	 ('Brassica rapa L. subsp. nipposinica','Mizuna, moutarde japonaise','maraîchère'),
	 ('Fragaria','Fraisier','maraîchère'),
	 ('Solanum tuberosum','Pomme de terre','maraîchère'),
	 ('Allium cepa var. aggregatum','Échalote','maraîchère'),
	 ('Cichorium intybus var. foliosum','Chicon/Endive','maraîchère'),
	 ('Helianthus tuberosus','Topinambour','maraîchère'),
	 ('Allium sativum','Ail','maraîchère'),
	 ('Allium ampeloprasum var. ampeloprasum','Ail éléphant','maraîchère');

COMMIT;