PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

INSERT INTO categorie (nom_categorie, descriptif) VALUES
	 ('Tomate rouge','Variétés de tomates rouges pour potager'),
	 ('Tomate de couleur','Variétés de tomates colorées et exotiques'),
	 ('Tomate cerise','Variétés de tomates cerises'),
	 ('Aubergines','Aubergines variétés anciennes bio'),
	 ('Concombres','Concombres variétés anciennes bio'),
	 ('Cornichons','Cornichons variétés anciennes bio'),
	 ('Potirons','Potirons variétés anciennes bio'),
	 ('Potimarrons','Potimarrons variétés anciennes bio'),
	 ('Courgettes','Courgettes variétés anciennes bio'),
	 ('Courges mini','Courges mini variétés anciennes bio'),
	 ('Melons','Melons variétés anciennes bio'),
	 ('Pastèques','Pastèques variétés anciennes bio'),
	 ('Piment','Piments variétés anciennes bio'),
	 ('Poivrons doux','Poivrons doux variétés anciennes bio'),
	 ('Fèves','Fèves variétés anciennes bio'),
	 ('Haricots nains filets','Haricots nains filets variétés anciennes bio'),
	 ('Haricots nains filets sans fil','Haricots nains filets sans fil variétés anciennes bio'),
	 ('Haricots nains à écosser','Haricots nains à écosser variétés anciennes bio'),
	 ('Haricots nains mangetout','Haricots nains mangetout variétés anciennes bio'),
	 ('Haricots à rames mangetout','Haricots à rames mangetout variétés anciennes bio'),
	 ('Haricots à rames à écosser','Haricots à rames à écosser variétés anciennes bio'),
	 ('Haricots beurre à rames','Haricots beurre à rames variétés anciennes bio'),
	 ('Haricots nains beurre','Haricots nains beurre variétés anciennes bio'),
	 ('Lentilles','Lentilles légumineuses anciennes variétés bio'),
	 ('Maïs','Maïs variétés anciennes pop corn doux bio'),
	 ('Pois nain mangetout','Pois nain mangetout variétés anciennes bio'),
	 ('Pois nain à écosser','Pois nain à écosser variétés anciennes bio'),
	 ('Pois à rames à écosser','Pois à rames à écosser variétés anciennes bio'),
	 ('Pois à rames mangetout','Pois à rames mangetout variétés anciennes bio'),
	 ('Basilic','Basilic variétés anciennes bio aromatiques'),
	 ('Coriandre','Coriandre variétés bio aromatiques'),
	 ('Persil','Persil variétés bio aromatiques'),
	 ('Roquette','Roquette variétés bio aromatiques salades'),
	 ('Sarriette','Sarriette variétés bio aromatiques médicinales'),
	 ('Perilla','Perilla variétés bio aromatiques asiatiques'),
	 ('Ail chinois','Ail chinois ciboulette variétés bio aromatiques'),
	 ('Angélique','Angélique variétés bio aromatiques médicinales'),
	 ('Ciboulette','Ciboulette variétés bio aromatiques'),
	 ('Fenouil','Fenouil variétés bio aromatiques médicinales'),
	 ('Mélisse','Mélisse variétés bio aromatiques médicinales'),
	 ('Menthe','Menthe variétés bio aromatiques médicinales'),
	 ('Oseille','Oseille variétés bio aromatiques légumes'),
	 ('Thym','Thym variétés bio aromatiques médicinales'),
	 ('Cerfeuil','Cerfeuil variétés bio aromatiques'),
	 ('Ciboule','Ciboule variétés bio aromatiques alliacées'),
	 ('Fenugrec','Fenugrec variétés bio légumineuses aromatiques'),
	 ('Per-cel','Per-cel ou céleri persil variétés bio aromatiques'),
	 ('Plante curry','Plante curry hélichryse variétés bio aromatiques médicinales'),
	 ('Verveine','Verveine variétés bio aromatiques médicinales'),
	 ('Marjolaine','Marjolaine variétés bio aromatiques médicinales'),
	 ('Aneth','Aneth variétés bio aromatiques médicinales'),
	 ('Ail des ours','Ail des ours variétés bio aromatiques médicinales'),
	 ('Origan','Origan variétés bio aromatiques médicinales'),
	 ('Camomille','Camomille variétés bio aromatiques médicinales'),
	 ('Livèche','Livèche variétés bio aromatiques médicinales'),
	 ('Sauge','Sauge variétés bio aromatiques médicinales'),
	 ('Armoise','Armoise variétés bio aromatiques médicinales'),
	 ('Betterave','Betterave variétés bio légumes racines'),
	 ('Carotte','Carotte variétés bio légumes racines'),
	 ('Navet','Navet variétés bio légumes racines'),
	 ('Cerfeuil tubéreux','Cerfeuil tubéreux variétés bio légumes racines'),
	 ('Oignon','Oignon variétés bio légumes bulbes'),
	 ('Panais','Panais variétés bio légumes racines'),
	 ('Radis','Radis variétés bio légumes racines'),
	 ('Salsifis','Salsifis variétés bio légumes racines'),
	 ('Artichaut','Artichaut variétés bio légumes fleurs'),
	 ('Céleri à côtes','Céleri à côtes variétés bio légumes tiges'),
	 ('Céleri à couper','Céleri à couper variétés bio légumes feuilles'),
	 ('Céleri-rave','Céleri-rave variétés bio légumes racines'),
	 ('Chicorée de Bruxelles/Chicon','Chicorée de Bruxelles chicon endive variétés bio légumes feuilles'),
	 ('Chicorée frisée et scarole','Chicorée frisée et scarole variétés bio légumes feuilles'),
	 ('Chicorée sauvage, pain de sucre et radicchio','Chicorée sauvage, pain de sucre et radicchio variétés bio légumes feuilles'),
	 ('Côte de bette','Côte de bette variétés bio légumes feuilles cardes'),
	 ('Épinard','Épinard variétés bio légumes feuilles'),
	 ('Chou brocoli','Chou brocoli variétés bio légumes fleurs inflorescences '),
	 ('Chou frisé Kale','Chou frisé kale variétés bio légumes feuilles hiver'),
	 ('Chou cabu blanc','Chou cabu blanc variétés bio légumes pommés'),
	 ('Chou cabu rouge','Chou cabu rouge variétés bio légumes pommés'),
	 ('Chou de Milan','Chou de Milan variétés bio légumes pommés feuilles cloquées'),
	 ('Chou chinois','Chou chinois variétés bio légumes feuilles asiatiques'),
	 ('Chou de Bruxelles','Chou de Bruxelles variétés bio légumes gemmiféres'),
	 ('Chou fleur','Chou fleur variétés bio légumes gemmiféres'),
	 ('Chou-navet Rutabaga','Chou-navet rutabaga variétés bio légumes racines'),
	 ('Chou-rave','Chou-rave variétés bio légumes tubéreux'),
	 ('Laitue à couper','Laitue à couper variétés bio légumes feuilles'),
	 ('Laitue pommée','Laitue pommée variétés bio pommes formées'),
	 ('Laitue romaine','Laitue romaine variétés bio pommes formées'),
	 ('Laitue batavia','Laitue batavia variétés bio pommes formées'),
	 ('Mâche','Mâche variétés bio rosettes'),
	 ('Poireau d''hiver','Poireau d''hiver variétés bio'),
	 ('Poireau d''été','Poireau d''été variétés bio'),
	 ('Rhubarbe','Rhubarbe variétés bio vivaces'),
	 ('Moutarde de Chine','Moutarde de Chine variétés bio feuilles'),
	 ('Salade asiatique','Salade asiatique variétés bio feuilles'),
	 ('Fraisier remontant','Fraisier remontant plants bio'),
	 ('Fraisier de printemps','Fraisier de printemps plants bio'),
	 ('Pomme de terre de conservation','Pomme de terre de conservation tubercules plants bio'),
	 ('Échalote','Échalote plants bio'),
	 ('Chicon/Endive - Racines chicon endive','Racines chicon endive plants bio'),
	 ('Topinambour - Tubercules','Topinambour tubercules plants bio'),
	 ('Ail - Ail variétés bio bulbes','Ail blanc, violet, productif, résistant froid, planté automne hiver');

COMMIT;